import type { Package } from "@/types/content"

export const packages: Package[] = [
  {
    id: "essential",
    name: "Essential",
    tagline: "Build a consistent, professional online presence. Done properly.",
    price: 3500,
    currency: "ZAR",
    billingCycle: "monthly",
    features: [
      "Monthly content plan aligned to your business goals",
      "8 branded social media posts",
      "1 carousel post (educational or authority-based)",
      "1 short-form video (reel)",
      "Caption writing and CTA structuring",
      "Post scheduling and publishing",
      "Basic engagement support (monitoring comments)",
      "Monthly performance summary",
      "30-minute monthly strategy check-in",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
  {
    id: "momentum",
    name: "Momentum",
    tagline: "Consistent content. Clear direction. Built to grow your presence.",
    price: 6000,
    currency: "ZAR",
    billingCycle: "monthly",
    highlight: true,
    features: [
      "Everything in Essential",
      "2 carousel posts (authority + education focused)",
      "2 short-form videos (reels)",
      "Content calendar planning for campaigns",
      "Lead-focused content strategy",
      "Comment + DM response handling",
      "Monthly analytics report with insights",
      "Campaign planning and content direction",
      "Improved CTA and positioning across content",
      "Priority support and communication",
      "Monthly strategy session",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
  {
    id: "authority",
    name: "Authority",
    tagline: "Full digital presence. Fully handled. Built for long-term growth.",
    price: 0,
    currency: "ZAR",
    billingCycle: "monthly",
    features: [
      "Everything in Momentum",
      "Long-form content (articles / thought leadership)",
      "Website content updates and optimisation",
      "Advanced campaign planning",
      "Brand positioning refinement",
      "Multi-platform content strategy",
      "Speaking / visibility opportunity research",
      "Ongoing strategic direction",
      "Dedicated support",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
]
