import type { Package } from "@/types/content"

export const packages: Package[] = [
  {
    id: "essential",
    name: "Essential",
    tagline: "Build a consistent, professional online presence. Done properly.",
    price: 3500,
    currency: "ZAR",
    billingCycle: "monthly",
    features: [
      "Monthly content plan aligned to your business goals",
      "2–3 branded posts per week across your platforms",
      "Caption writing and CTA structuring",
      "Post scheduling and publishing",
      "Monthly performance summary",
      "30-minute monthly strategy check-in",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
  {
    id: "momentum",
    name: "Momentum",
    tagline: "Consistent content. Clear direction. Built to grow your presence.",
    price: 6000,
    currency: "ZAR",
    billingCycle: "monthly",
    highlight: true,
    features: [
      "Everything in Essential",
      "4–5 branded posts per week across your platforms",
      "Lead-focused content strategy",
      "Comment + DM response handling",
      "Monthly analytics report with insights",
      "Priority support and monthly strategy session",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
  {
    id: "authority",
    name: "Authority",
    tagline: "Full digital presence. Fully handled. Built for long-term growth.",
    price: 0,
    currency: "ZAR",
    billingCycle: "monthly",
    features: [
      "Everything in Momentum",
      "Long-form content and thought leadership",
      "Website content updates and optimisation",
      "Brand positioning and multi-platform strategy",
      "Visibility and speaking opportunity research",
      "Dedicated support and ongoing strategic direction",
    ],
    cta: { label: "Book a demo", action: "cal" },
  },
]
